### ISSUE TITLE
jtable dosen't subbort utf-8

### ISSUE THREAD

**Issue by mmabas77** [atarw/material-ui-swing#42] opened 2018-08-24 11:22 UTC
i tried to write in Arabic in the head of a jtable but it appears in a wrong way.
![untitled](https://user-images.githubusercontent.com/42513916/44575939-9bbecc00-a78d-11e8-930b-95a88498961a.png)
it should be like that
![untitled1](https://user-images.githubusercontent.com/42513916/44576010-cdd02e00-a78d-11e8-8b03-0926fd610ca1.png)

**Comment by vincenzopalazzo** [comment] 2018-08-24 17:59
Hi @mmabas77 , I have news then.
I'll tell you the problem so if someone else has the same problem can find help in this answer.
The problem is that the font did not support Arabic because we used "Roboto", now I added the Arabic version of the google font but I had to change the typology and I added "Noto" not having the possibility to try the support in the whole Arabic with the font I ask you if you can try my solution where you find the jar to the link [https://github.com/vincenzopalazzo/material-ui-swing/blob/add_support_font/lib/material-ui-swing.jar](url)

I do not make the pull request because maybe @atarw  has a better solution and sincerely me too but I just have to understand how to generalize everything in the code.
For the moment in my case the support to Arabic works but I would like you to do a more thorough test.
I hope it works and you can get on with your work until the final version of font support arrives

ps: The code will be updated even if it works because it is written in a horrible way and above all because you can do better, my solution is a temporary solution because I had little time because I'm going on vacation

link branch support fonts: [https://github.com/vincenzopalazzo/material-ui-swing/tree/add_support_font](url)

**Comment by atarw** [comment] 2018-08-25 01:45
I think it's best to switch to [Noto Sans](https://www.google.com/get/noto/) since they seem to support the most languages while still looking "Googley".

They have an [Arabic font](https://www.google.com/get/noto/#sans-arab), and a standard [English font](https://www.google.com/get/noto/#sans-lgc). Google also provides [a tool](https://github.com/googlei18n/nototools/blob/master/nototools/merge_noto.py) for merging these fonts into one file, which I can try to run this evening.

Of course as more languages get added, this strategy might need to change since the Noto page says the total size of all the fonts is 1 GB

**Comment by atarw** [comment] 2018-08-25 06:37
Pushed the fix

**Closed by atarw** 2018-08-25 06:37 UTC

**Comment by vincenzopalazzo** [comment] 2018-08-25 13:38
@atarw In fact, I saw that there are many familiar family fonts so a 1.1 GB of space only for fonts seems exaggerated even for me hahaha.

I'm really in love with the font Roboto and so I preferred to leave the swinch of the character only in case you encounter an unsupported language (in our case the Arabic)
I decided to leave as a main font because I believe my pixelated pixelated in the language other than the Arabic

come in these two screens
Roboto
![uno](https://user-images.githubusercontent.com/17150045/44618764-8bd1e580-a87c-11e8-8e97-eec543e3c785.png)

Noto
![due](https://user-images.githubusercontent.com/17150045/44618767-9ee4b580-a87c-11e8-9a39-d408ad67b10b.png)

I hope that from the photo you can see the difference

ps: I would like to combine different fonts with the robotic one, as you suggested, I found an interesting software (fontForge), we'll see what will come out of it

**Comment by atarw** [comment] 2018-08-25 17:06
The issue with activating with locale is that if a user's computer set to, say, US English opens something with Arabic text then it won't work.

You could try combining Roboto and the Noto Sans Arabic fonts using Font Forge (FWIW [Google itself uses Noto as a fallback font since Roboto doesn't support Arabic](https://stackoverflow.com/questions/52006088/roboto-does-not-display-correctly-with-the-arabic-language))

**Comment by atarw** [comment] 2018-08-26 06:26
Have fun!!
