### ISSUE TITLE
NPE on application exit if JTextField has focus

### ISSUE THREAD

**Issue by ColoredCarrot** [atarw/material-ui-swing#55] opened 2019-01-20 20:08 UTC
When exiting the application, a `NullPointerException` is thrown if a `JTextField` is focused.

Presumably, this is because the field loses focus, thus the `MaterialTextFieldUI` tries to change color (note how a focused text field will display a blue line at the bottom); however, the `Graphics` object passed to `getComponentGraphics` is null.

A quick fix might be a simple change in `MaterialTextFieldUI.changeColorOnFocus(boolean)`:
```
//c.paint(c.getGraphics());
if (c.getGraphics() != null) c.paint(c.getGraphics());
```
_(I don't have time to make a pull request right now)_

**Stacktrace:**
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.JComponent.getComponentGraphics(JComponent.java:740)
	at javax.swing.JComponent.paint(JComponent.java:1001)
	at mdlaf.components.textfield.MaterialTextFieldUI.changeColorOnFocus(MaterialTextFieldUI.java:104)
	at mdlaf.components.textfield.MaterialTextFieldUI.focusLost(MaterialTextFieldUI.java:96)
	at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:230)
	at java.awt.Component.processFocusEvent(Component.java:6425)
	at java.awt.Component.processEvent(Component.java:6289)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1024)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:690)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at sun.awt.SunToolkit$1.run(SunToolkit.java:518)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vincenzopalazzo** [comment] 2019-01-20 20:32
Hello @ColoredCarrot,

I have noted this problem, I will fix the problem in the next hours, in the nex update I will introduce a difensive program in the all code

Thanks for your help.

**Comment by ColoredCarrot** [comment] 2019-01-20 20:35
Hey @vincenzopalazzo.

thanks for the quick response! I'm looking forward to the fix. Keep up the great work with this library :grin:

**Comment by vincenzopalazzo** [comment] 2019-01-20 20:51
@ColoredCarrotI I fixed in the my repo the problem, if the problem is resoluted i will init a fix in the original branch.

The jar whit fix is [here](https://github.com/vincenzopalazzo/material-ui-swing/releases).

**Comment by vincenzopalazzo** [comment] 2019-01-20 20:58
@ColoredCarrot Let me know if I can deal with the pull request.

**Comment by ColoredCarrot** [comment] 2019-01-20 20:59
> @ColoredCarrot Let me know if I can deal with the pull request.

Sure, of course

**Comment by ColoredCarrot** [comment] 2019-01-20 21:37
> @ColoredCarrot The problem is not fix, I'll try to find the problem, I'm sorry

Alright, no problem, take your time; I much prefer a complete fix than a rushed "bodge" :laughing:

**Comment by vincenzopalazzo** [comment] 2019-01-20 21:58
@ColoredCarrot the jar fix is now disponible [here](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V9.6.1)

**Comment by atarw** [comment] 2019-01-21 03:46
Thanks for fixing it!

**Closed** 2019-01-21 03:46 UTC

**Comment by vincenzopalazzo** [comment] 2019-01-21 09:15
@atarw not to thank me is a pleasure
