### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by lovechenghao** [atarw/material-ui-swing#92] opened 2019-11-13 15:40 UTC
Chinese garbled, as shown

**Comment by vincenzopalazzo** [comment] 2019-11-13 15:46
Hi @lovechenghao it the same repository of https://github.com/vincenzopalazzo/material-ui-swing

The issue is fixed by this issue https://github.com/vincenzopalazzo/material-ui-swing/issues/87

**Comment by lovechenghao** [comment] 2019-11-14 00:57
![](https://user-images.githubusercontent.com/29998950/68817452-bcd64a00-06bc-11ea-9348-cc420032227c.png)

**Closed** 2019-11-14 00:59 UTC
