### ISSUE TITLE
Mouse Cursor

### ISSUE THREAD

**Issue by amirheclown** [atarw/material-ui-swing#94] opened 2020-01-13 14:41 UTC
hello and good day.
If you drag the mouse between 2 panels or SplitPanes to maximize or minimize a field, the mouse cursor is not changed and is not shown as a line so that the resize can be made easier.

**Comment by vincenzopalazzo** [comment] 2020-01-13 21:07
Hi @amirheclown, good day.

Can you update a screenshot of the problem or you can update a minimal example?

I have tested the library inside the demo (you can find it [here](https://github.com/atarw/material-ui-swing/releases/download/v1.1.1-beta/Demo-Swing-set3.tar)) and it worked.

You can test the SplitPane here

![Screenshot from 2020-01-13 21-58-10](https://user-images.githubusercontent.com/17150045/72291785-5d5ed100-3650-11ea-9cd3-6f3db26612f3.png)

For reproducing the problem I have to need the 

- Operative System;
- Java version;
- Minimal example or use case inside the demo to reproduce the problem.

Thanks for your time and thanks for your work.

**Comment by amirheclown** [comment] 2020-01-14 12:17
Hi there. Thank you for your prompt reply. I expect mouse behavior like in this picture. But the mouse cursor does not change.

My Operative System: Windows 7 Professional
Java Version: 12

![inter-mouse-image30](https://user-images.githubusercontent.com/44499425/72343841-1e706000-36d0-11ea-80ff-f086e617f4fd.png)

**Comment by vincenzopalazzo** [comment] 2020-01-14 20:43
Hi @amirheclown,

Thanks for your information, but I can't reproduce the problem; can you post the minimal example reproducible with the code?

**Comment by vincenzopalazzo** [comment] 2020-01-17 11:08
HI @amirheclown,

I'm working on JSplitPane Style and I'm trying to reproduce your problem bug I have this result

![](https://media.giphy.com/media/VEntFi4tQLmztCnHMc/giphy.gif)

**Comment by vincenzopalazzo** [comment] 2020-03-08 23:32
I'm marking this issue of how not-reproducible and I'm closing it.

**Closed by vincenzopalazzo** 2020-03-08 23:32 UTC
Labels: requested more details
