### ISSUE TITLE
JSpinner is not working

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#80] opened 2019-04-10 12:51 UTC
Currently clicking on the Spinner buttons won't change anything

![GIFSpinner](https://user-images.githubusercontent.com/4528294/55879965-1105d280-5ba0-11e9-9a31-57cbb9a638b4.gif)

**Comment by vincenzopalazzo** [comment] 2019-04-10 16:14
Ciao @ Reap00r, questo bug era corretto nella prossima versione, il problema è il MaterialManagerListner quando il look and fell crea il pulsante per jspinner, la versione corretta è in dir lib per il mio progetto di versione, creerò una richiesta pull con tutte le correzioni

**Comment by vincenzopalazzo** [comment] 2019-04-10 16:14
Hi @Reap00r, this bug was correct into next versione, the problem is the MaterialManagerListner when the look and fell create the button for jspinner, the versione correct is into dir lib for my version project, I will create a pull request with all fix

**Comment by vincenzopalazzo** [comment] 2019-04-12 22:58
Hi @Reap00r, Sorry if I'm late with the pull request, by next weekend I will carry out the alignment with the status, you can meanwhile see the changes in my repo, sorry again for the delay

**Comment by Reap00r** [comment] 2019-04-15 10:36
Hi @vincenzopalazzo,
don't worry, I am working on a different project so unfortunately I don't have much time for this currently.

**Comment by vincenzopalazzo** [comment] 2019-04-15 10:54
Hi @Reap00r 
I am in the same situation, good job

**Comment by vincenzopalazzo** [comment] 2019-04-21 13:16
Now I Creating a pull request, the pull request resolve this problem, @atarw can you close this issue, please?

**Closed** 2019-04-21 23:20 UTC
